#!/bin/bash
#
# olmOCR Frontend Configuration Script
#
# This script configures and rebuilds the frontend with Firebase credentials
# Run this after the main deploy.sh and after setting up Firebase.
#
# Usage:
#   ./configure-frontend.sh
#
# You will be prompted for Firebase configuration values.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ID="${GCP_PROJECT_ID:-juniper-core}"
REGION="${GCP_REGION:-us-central1}"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo_header() { echo -e "\n${BLUE}========================================${NC}"; echo -e "${BLUE}$1${NC}"; echo -e "${BLUE}========================================${NC}"; }
echo_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
echo_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
echo_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# ============================================
# Get Backend URL
# ============================================
echo_header "olmOCR Frontend Configuration"

BACKEND_URL=$(gcloud run services describe olmocr-backend --region "$REGION" --format='value(status.url)' 2>/dev/null || echo "")

if [ -z "$BACKEND_URL" ]; then
    echo_error "Backend service not found. Run deploy.sh first."
    exit 1
fi

echo_info "Backend URL: $BACKEND_URL"
echo ""

# ============================================
# Get Firebase Configuration
# ============================================
echo_header "Firebase Configuration"
echo ""
echo "Please enter your Firebase configuration values."
echo "Get these from: Firebase Console > Project Settings > Your Apps > Web App"
echo ""

read -p "Firebase API Key: " FIREBASE_API_KEY
read -p "Firebase Auth Domain (e.g., ${PROJECT_ID}.firebaseapp.com): " FIREBASE_AUTH_DOMAIN
FIREBASE_AUTH_DOMAIN="${FIREBASE_AUTH_DOMAIN:-${PROJECT_ID}.firebaseapp.com}"
read -p "Firebase Project ID [${PROJECT_ID}]: " FIREBASE_PROJECT_ID
FIREBASE_PROJECT_ID="${FIREBASE_PROJECT_ID:-${PROJECT_ID}}"
read -p "Firebase Storage Bucket (e.g., ${PROJECT_ID}.appspot.com): " FIREBASE_STORAGE_BUCKET
FIREBASE_STORAGE_BUCKET="${FIREBASE_STORAGE_BUCKET:-${PROJECT_ID}.appspot.com}"
read -p "Firebase Messaging Sender ID: " FIREBASE_MESSAGING_SENDER_ID
read -p "Firebase App ID: " FIREBASE_APP_ID

if [ -z "$FIREBASE_API_KEY" ] || [ -z "$FIREBASE_APP_ID" ]; then
    echo_error "Firebase API Key and App ID are required."
    exit 1
fi

# ============================================
# Create .env file
# ============================================
echo_header "Creating Frontend Configuration"

cat > "$SCRIPT_DIR/gcp-frontend/.env" << EOF
# olmOCR Frontend Configuration
# Generated by configure-frontend.sh on $(date)

# API Configuration
VITE_API_URL=${BACKEND_URL}/api

# Firebase Configuration
VITE_FIREBASE_API_KEY=${FIREBASE_API_KEY}
VITE_FIREBASE_AUTH_DOMAIN=${FIREBASE_AUTH_DOMAIN}
VITE_FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
VITE_FIREBASE_STORAGE_BUCKET=${FIREBASE_STORAGE_BUCKET}
VITE_FIREBASE_MESSAGING_SENDER_ID=${FIREBASE_MESSAGING_SENDER_ID}
VITE_FIREBASE_APP_ID=${FIREBASE_APP_ID}

# Feature Flags
VITE_ENABLE_GOOGLE_LOGIN=true
VITE_MAX_UPLOAD_SIZE_MB=100
EOF

echo_info "Created gcp-frontend/.env"

# ============================================
# Rebuild and Deploy Frontend
# ============================================
echo_header "Rebuilding Frontend"

REGISTRY="${REGION}-docker.pkg.dev/${PROJECT_ID}/olmocr"
cd "$SCRIPT_DIR"

echo_info "Building frontend with new configuration..."
gcloud builds submit \
    --tag "${REGISTRY}/frontend:latest" \
    --timeout=20m \
    -f gcp-frontend/Dockerfile \
    . --quiet

echo_info "Deploying updated frontend..."
gcloud run deploy olmocr-frontend \
    --image "${REGISTRY}/frontend:latest" \
    --platform managed \
    --region "$REGION" \
    --allow-unauthenticated \
    --port 8080 \
    --memory 256Mi \
    --cpu 1 \
    --min-instances 0 \
    --max-instances 10 \
    --quiet

FRONTEND_URL=$(gcloud run services describe olmocr-frontend --region "$REGION" --format='value(status.url)')

# ============================================
# Update Backend CORS
# ============================================
echo_header "Updating Backend CORS"

echo_info "Updating backend with frontend URL..."
gcloud run services update olmocr-backend \
    --region "$REGION" \
    --update-env-vars "CORS_ORIGINS=${FRONTEND_URL}" \
    --quiet

# ============================================
# Complete
# ============================================
echo_header "Configuration Complete!"

echo ""
echo -e "Frontend URL: ${GREEN}$FRONTEND_URL${NC}"
echo -e "Backend URL:  ${GREEN}$BACKEND_URL${NC}"
echo ""
echo_info "Your olmOCR application is now fully configured!"
echo ""
echo "You can access it at: $FRONTEND_URL"
echo ""
echo "Default login:"
echo "  - Create a new account using email/password"
echo "  - Or use Google Sign-In if you enabled it in Firebase"
echo ""
